name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in afflift posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://afflift.com/f/forums/-/index.rss"
          max_post_count: 20
          comment_tag_name: "afflift"
      - name: Pull in 无忧分享 posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://51.ruyo.net/feed"
          max_post_count: 5
          comment_tag_name: "ruyo"
      - name: Pull in sspai posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://sspai.com/feed"
          max_post_count: 10
          comment_tag_name: "sspai"

